
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 22 15:48:51 CET 2021
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int NUMBER = 4;
  public static final int SEMI = 3;
  public static final int EOF = 0;
}

