
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 04 19:09:22 CEST 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int PLUS = 3;
  public static final int NUMBER = 6;
  public static final int MINUS = 4;
  public static final int SEMI = 2;
  public static final int TIMES = 5;
  public static final int EOF = 0;
}

