
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 29 15:14:37 CEST 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int MOD = 7;
  public static final int IDENTIFIERADR = 20;
  public static final int PLUS = 3;
  public static final int LEFT_PAREN = 9;
  public static final int DECIMAL = 17;
  public static final int SEMI = 2;
  public static final int LEFT_CURLY = 11;
  public static final int IDENTIFIER = 18;
  public static final int RETURN = 14;
  public static final int VOID_TYPE = 23;
  public static final int EQUALS = 8;
  public static final int DECIMAL_TYPE = 22;
  public static final int COMMA = 13;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int INT_TYPE = 21;
  public static final int PROTOTYPE = 15;
  public static final int INTEGER = 16;
  public static final int IDENTIFIERVAL = 19;
  public static final int RIGHT_PAREN = 10;
  public static final int RIGHT_CURLY = 12;
}

