
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 18 21:59:44 CEST 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int DECIMAL = 10;
  public static final int INTEGER = 9;
  public static final int DIVIDE = 6;
  public static final int INT_TYPE = 12;
  public static final int MOD = 7;
  public static final int DECIMAL_TYPE = 13;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int error = 1;
  public static final int IDENTIFIER = 11;
  public static final int TIMES = 5;
  public static final int EQUALS = 8;
}

